@EventDrivenCheckout.Basket_HostAddress = http://localhost:5238

### 1. Add item to basket
POST {{EventDrivenCheckout.Basket_HostAddress}}/api/additem
Content-Type: application/json

{
  "userId": "user-1",
  "productId": "p-1",
  "name": "Stick",
  "price": 250,
  "quantity": 2
}

### 2. Add some more
POST {{EventDrivenCheckout.Basket_HostAddress}}/api/additem
Content-Type: application/json

{
  "userId": "user-1",
  "productId": "p-2",
  "name": "Stone",
  "price": 120,
  "quantity": 1
}

### 3a. Checkout
POST {{EventDrivenCheckout.Basket_HostAddress}}/api/checkout
Content-Type: application/json

{
  "userId": "user-1",
  "triggerFailure": false
}

### 3b. Checkout with simulated failure
POST {{EventDrivenCheckout.Basket_HostAddress}}/api/checkout
Content-Type: application/json

{
  "userId": "user-1",
  "triggerFailure": true
}